# -*- coding: utf-8 -*-
"""DNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W6oBaAjcLHHmDmxJEn0jqaje3rBb1ocM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import tensorflow as tf
# from tensorflow import keras
# from tensorflow.keras import layers
# !pip install tensorflowjs
# !pip install git+https://github.com/tensorflow/docs
# import tensorflow_docs as tfdocs
# import tensorflow_docs.modeling

from google.colab import files
files.upload()
data = pd.read_csv("data_CBR.csv", sep=";")
dataset = data.values
input_data = dataset[:,0:6]
output_data = dataset[: ,6:9]

def build_model():
  model = keras.Sequential([
    layers.Dense(3, activation="relu", input_shape=[6]),
    layers.Dense(9, activation="sigmoid"),
    layers.Dense(3)])
  optimizer = tf.keras.optimizers.RMSprop(0.001)
  model.compile(loss="mae", optimizer=optimizer, metrics=["mse", "mape", "msle", "logcosh"])
  return model
model = build_model()
history = model.fit(input_data, output_data, validation_split=0.2, epochs=8000, verbose=0, callbacks=[tfdocs.modeling.EpochDots()])
model.save("complete_model_saved.h5")
!mkdir output_folder
!tensorflowjs_converter --input_format keras complete_model_saved.h5 output_folder
!ls output_folder

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend(["Training", "Testing"], loc="upper right")

plt.plot(history.history["mse"])
plt.plot(history.history["val_mse"])
plt.xlabel("Epoch")
plt.ylabel("Mean squared error")
plt.legend(["Training", "Testing"], loc="upper right")

plt.plot(history.history["mape"])
plt.plot(history.history["val_mape"])
plt.xlabel("Epoch")
plt.ylabel("Mean absolute percentage error")
plt.legend(["Training", "Testing"], loc="upper right")

plt.plot(history.history["msle"])
plt.plot(history.history["val_msle"])
plt.xlabel("Epoch")
plt.ylabel("Mean squared logarithmic error")
plt.legend(["Training", "Testing"], loc="upper right")

plt.plot(history.history["logcosh"])
plt.plot(history.history["val_logcosh"])
plt.xlabel("Epoch")
plt.ylabel("Logarithm of the hcos of the prediction errorr")
plt.legend(["Training", "Testing"], loc="upper right")

D10 = 0.171
D30 = 0.462
D50 = 1.081
D60 = 1.445
CU = 8.450
CC = 0.864
matrix_size = np.zeros((1, 3))
matrix = np.zeros_like(matrix_size, dtype=float)
matrix[0, :] = model.predict(np.array([[D10, D30, D50, D60, CU, CC]]))
print(matrix)